name: buildandtest

on: push

jobs:

  build:

    name: Build and test program
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - run: |
          cd lab1/
          make lab1test

      - run: |
           cd lab1/
          ./lab_1_test
