name: buildandtest

on: push

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Build1
        run: |
          cd lab1/
          make lab1test
          ./test
      
      - name: Build2
        run: |
          cd lab_2/21
          make lab2test
          ./test
           cd ../22
          make test
          ./test
          
      - name: Build3
        run: |
          cd lab3/
          make lab3test
          ./test
          
      - name: Build4
        run: |
          cd lab4/4_1
          make lab4_1test
          ./test
          cd ../4_2
          make lab4_2test
          ./test
          
      - name: Build5
        run: |
          cd lab5/
          make lab5test
          ./test5
          
      - name: Build6
        run: |
          cd lab6/
          make lab6test
          ./test6
          
      - name: Build71
        run: |
          cd lab7pr/
          make lab7test
          ./test7
          
      - name: coverage
        run: | 
          cd lab7pr
          CODECOV_TOKEN='60085b7b-22a9-42d0-aa59-d7d1f44aec06'
          bash <(curl -s https://codecov.io/bash)
